spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000

app:
  cache:
    cache-names:
      - bookByCategoryName
      - bookByNameAndAuthor
    caches:
      bookByCategoryName:
        expiry: 1m
      bookByNameAndAuthor:
        expiry: 1m

